version: '3.8'

services:
  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_AUTOMOTA=${TELEGRAM_AUTOMOTA}
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - ENVIRONMENT=production
    restart: unless-stopped